purge:
  trigger: time # TODO: change to 'space' or 'count' if preferred
  max_backups_count: 25
  max_backups_space: 5
  max_backups_time: 120
profiles:
  -
    name: Datenbackup
    root: /user
    exclude_paths: ".github\n/data/tntsearch/\n/plugins\n/themes/quark\n/themes/hadron"
    exclude_files: ".DS_Store\n.git\n.svn\n.hg\n.idea\n.vscode\nnode_modules"
    schedule: true
    schedule_at: '0 0 * * 1' # every Monday at midnight
    #schedule_at: '0 2 * * *' # every day at 2am
    #schedule_at: '0 0/12 * * *' # every 12 hours at midnight and noon
  -
    name: Systembackup
    root: /
    exclude_paths: ".github\n.phan\n/backup\n/cache\n/docs\n/images\n/tests\n/tmp\n/vendor"
    exclude_files: ".DS_Store\n.git\n.svn\n.hg\n.idea\n.vscode\nnode_modules"
    schedule: true
    schedule_at: '0 0 1 * *' # first day of every month at midnight
    #schedule_at: '0 0 * * 1' # every Monday at midnight
    #schedule_at: '0 0 1 1/3 *' # every 3 months on the first day at midnight
