website:
  enabled: true
  readableName: 'Website Login'
  description: 'Can log in to the website and view protected pages'
  access:
    site:
      login: true
admin:
  enabled: true
  readableName: 'Admin Login'
  description: 'Can log in to the admin panel and access the API'
  access:
    api:
      access: true
      users:
        read: true
accounts:
  enabled: true
  readableName: 'Account Manager'
  description: 'Can manage user accounts and groups'
  access:
    api:
      users:
        read: true
        write: true
editor:
  enabled: true
  readableName: 'Content Editor'
  description: 'Can edit content on the site, including pages and media'
  access:
    api:
      pages:
        read: true
        write: true
      media:
        read: true
      system:
        write: true
maintainer:
  enabled: true
  readableName: 'Site Maintainer'
  description: 'Can manage restricted parts of the site & see relevant system information'
  access:
    api:
      system:
        read: true
        write: true
      gpm:
        read: true
      scheduler:
        read: true
      pages:
        read: true
        write: true
      media:
        read: true
        write: true
manager:
  enabled: true
  readableName: 'Site Manager'
  description: 'Can manage the site as a whole themselves. DO ONLY GRANT TO TRAINED & EXPERIENCED USERS!'
  access:
    api:
      pages:
        read: true
        write: true
      media:
        read: true
        write: true
      config:
        read: true
        write: true
      system:
        read: true
        write: true
        backup: true
      gpm:
        read: true
        write: true
      scheduler:
        read: true
        write: true
      reports:
        read: true
      webhooks:
        read: true
        write: true
      flex-objects:
        list: true
statistics:
  enabled: true
  readableName: 'Site Statistics'
  description: 'Can see site statistics'
  access:
    api:
      reports:
        read: true
      system:
        read: true
