title: Hadron
default_lang: en
author:
  name: 'Crabston GmbH'
  email: hadron@crabston.dev
taxonomies:
  - category
  - tag
  - month
  - author
  - filter
metadata:
  description: 'Hadron is a Grav theme and skeleton that serves as a template for websites and webshops for beginners, but can also be used by professionals as a basis for complex projects.'
  keywords: 'grav, grav2, grav-theme, grav-skeleton, hadron, website, webshop, website cms, webshop cms, ecommerce tool, cms, website creator'
