title: Hadron
default_lang: en
author:
  name: 'Crabston GmbH'
  email: hadron@crabston.dev
taxonomies:
  - category
  - tag
  - month
  - author
  - filter
metadata:
  description: 'Hadron is more than a modern and customizable Grav theme and skeleton. On the one hand, it is optimized for beginners to quickly create a simple website, but on the other hand, it is also suitable for professionals who want to use Hadron as a foundation for a complex website with self-developed functions.'
  keywords: 'hadron, grav, grav2, grav-theme, grav-skeleton, quark2, website, webshop, website cms, webshop cms, ecommerce cms, modern, fast, customizable, responsive, seo optimized'
