streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
       - user/themes/local
       - user/themes/hadron
       - user/themes/quark-open-publishing # TODO: remove
       - user/themes/quark
